metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
- module: elasticsearch
  metricsets:
    - node
    - node_stats
    #- index
    #- index_recovery
    #- index_summary
    #- shard
    #- ml_job
  period: 10s
  hosts: ["elasticsearch:9200"]

#processors:
#  - add_docker_metadata:
#      host: "unix:///host_docker/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]

http.enabled: true
http.host: 0.0.0.0