filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.txt
  multiline.type: pattern
  multiline.pattern: '^[[:digit:]]'
  multiline.negate: true
  multiline.match: after


output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"